src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $azureId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $displayName;

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $language;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $jobTitle;

    /**
     * @ORM\Column(type="string", length=2, nullable=true)
     */
    private $countryWorkplace;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLoginAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToMany(targetEntity=Group::class, inversedBy="users")
     */
    private $groups;

    public function __construct()
    {
        $this->setIsActive(true);
        $this->groups = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = new ArrayCollection();
        // guarantee every user at least has ROLE_USER
        // Default role/permissions
        $roles->add('ROLE_USER');

        foreach ($this->getGroups() as $group) {
            foreach ($group->getRoles() as $role) {
                $roles->add($role);
            }
        }

        return array_unique($roles->toArray());
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAzureId(): ?string
    {
        return $this->azureId;
    }

    public function setAzureId(?string $azureId): self
    {
        $this->azureId = $azureId;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    public function setDisplayName(?string $displayName): self
    {
        $this->displayName = $displayName;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?string $jobTitle): self
    {
        $this->jobTitle = $jobTitle;

        return $this;
    }

    public function getCountryWorkplace(): ?string
    {
        return $this->countryWorkplace;
    }

    public function setCountryWorkplace(?string $countryWorkplace): self
    {
        $this->countryWorkplace = $countryWorkplace;

        return $this;
    }

    public function setExtraInfo(?array $extraInfo): self
    {
        if (!empty($extraInfo['preferredLanguage'])) {
            $this->setLanguage(strtolower(substr($extraInfo['preferredLanguage'], 0, 2)));
        }

        if (!empty($extraInfo['preferredLanguage'])) {
            preg_match('/\[([A-Z]{2})\]$/', $extraInfo['officeLocation'], $countryWorkplace);
            if (!empty($countryWorkplace[1])) {
                $this->setCountryWorkplace($countryWorkplace[1]);
            }
        }

        if (!empty($extraInfo['jobTitle'])) {
            $this->setJobTitle($extraInfo['jobTitle']);
        }

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeInterface
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(?\DateTimeInterface $lastLoginAt): self
    {
        $this->lastLoginAt = $lastLoginAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection|Group[]
     */
    public function getGroups(): Collection
    {
        return $this->groups;
    }

    public function addGroup(Group $group): self
    {
        if (!$this->groups->contains($group)) {
            $this->groups[] = $group;
            $group->addUser($this);
        }

        return $this;
    }

    public function removeGroup(Group $group): self
    {
        if ($this->groups->contains($group)) {
            $this->groups->removeElement($group);
            $group->removeUser($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->displayName;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'app.homepage.title'|trans }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1 class="display-4">Welcome to {{ 'app.name'|trans }}</h1>
                <p class="lead">{{ 'app.description'|trans }}</p>
                <hr class="my-4">
                <div class="row">
                    <div class="col-md-3">
                        <div class="alert alert-primary">
                            alert-primary
                        </div>
                        <a href="#" class="btn btn-primary">btn-primary</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-secondary">
                            alert-secondary
                        </div>
                        <a href="#" class="btn btn-secondary">btn-secondary</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-light">
                            alert-light
                        </div>
                        <a href="#" class="btn btn-light">btn-light</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-dark">
                            alert-dark
                        </div>
                        <a href="#" class="btn btn-dark">btn-dark</a><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="alert alert-success">
                            alert-success
                        </div>
                        <a href="#" class="btn btn-success">btn-success</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-info">
                            alert-info
                        </div>
                        <a href="#" class="btn btn-info">btn-info</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-warning">
                            alert-warning
                        </div>
                        <a href="#" class="btn btn-warning">btn-warning</a><br><br>
                    </div>
                    <div class="col-md-3">
                        <div class="alert alert-danger">
                            alert-danger
                        </div>
                        <a href="#" class="btn btn-danger">btn-danger</a><br><br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <a class="btn btn-outline-secondary btn-lg" href="{{ path("secure") }}" role="button">
                            <i class="fa fa-cog"></i> {{ 'app.menu.main.secure'|trans }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index/secure.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'app.homepage.title'|trans }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1 class="display-4">Welcome to {{ 'app.name'|trans }}</h1>
                <p class="lead">{{ 'app.description'|trans }}</p>
                <hr class="my-4">
                     <div class="row">
                    <div class="col-md-12 text-center">
                        {% if app.user %}
                            <div class="mb-3">
                                <p>You are logged in as {{ app.user.displayName }}</p>
                                <table class="table table-responsive-lg table-striped">
                                    <tr>
                                        <td>ID</td>
                                        <td>{{ app.user.id }}</td>
                                    </tr>
                                    <tr>
                                        <td>Azure ID</td>
                                        <td>{{ app.user.azureId|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Display name</td>
                                        <td>{{ app.user.displayName }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td>{{ app.user.username }}</td>
                                    </tr>
                                    <tr>
                                        <td>Job title</td>
                                        <td>{{ app.user.jobTitle|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Country workplace</td>
                                        <td>{{ app.user.countryWorkplace|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Language</td>
                                        <td>{{ app.user.language|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Roles</td>
                                        <td class="data-role">{{ app.user.roles|join(' | ')|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Last login</td>
                                        <td>{{ app.user.lastLoginAt|date()|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Created at</td>
                                        <td>{{ app.user.createdAt|date()|default('-') }}</td>
                                    </tr>
                                    <tr>
                                        <td>Updated at</td>
                                        <td>{{ app.user.updatedAt|date()|default('-') }}</td>
                                    </tr>
                                </table>

                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}